### ISSUE TITLE
Multiple image support

### ISSUE THREAD

**Issue by Muhammad-Owais-Warsi** [Muhammad-Owais-Warsi/Poemify#14]
**Please describe.**
Currently the app just take single image from user . We can add functionality of taking multiple images at once. 

**Describe the solution you'd like**
We can add functionality of taking multiple images at once.

**Additional context**
NA

**Comment by shreyash3087** [comment]
@Muhammad-Owais-Warsi 

[multiImage.webm](https://github.com/Muhammad-Owais-Warsi/Poemify/assets/72603662/65a8bb00-e947-484c-b440-0779782cf4df)

Something Like This?

**Comment by Muhammad-Owais-Warsi** [comment]
Great work @shreyash3087 .Exactly, but how you'll manage to send these images to ai and get the response.
Btw I'll assign this to you

**Comment by shreyash3087** [comment]
@Muhammad-Owais-Warsi instead of a single image,simply converted it into an array of images,it works fine and the poem is generated with the combination of both the images,but i somehow broke the poemText component =) ,it doesnt show the generated text,will fix that and then raise a PR-


https://github.com/Muhammad-Owais-Warsi/Poemify/assets/72603662/31f7e64f-41ae-4496-ae64-13c693d04323


Edit: I got it the poem's format is incorrect cuz i was working on a older copy of the repo,it works now yay =)

**Comment by Muhammad-Owais-Warsi** [comment]
That is great @shreyash3087.
